# 运行截图测试
name: UI Tests

on: [push]

jobs:
  run-ui-test:
    name: Run UI tests
    runs-on: macos-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests with Coverage
        run: |
          pnpm ui:test

       - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: backstop_data
